export * from "@/pages/Home/Home";
export * from "@/pages/Home/Transportation";
export * from "@/pages/Home/Consulting";
export * from "@/pages/Home/OilAndGas";
export * from "@/pages/AboutUs/AboutUs";
// export * from "@/pages/AboutUs/AboutUsTheTeam";
// export * from "@/pages/AboutUs/AboutUsOEMPartners";
export * from "@/pages/profile";
export * from "@/pages/sign-in";
export * from "@/pages/sign-up";
export * from "@/pages/Services/Services";
export * from "@/pages/Projects/Projects";
export * from "@/pages/Events/Events";
export * from "@/pages/Careers/Careers";
export * from "@/pages/ContactUs/ContactUs";
export * from "@/pages/Home/Consulting";
export * from "@/pages/Home/Transportation";
export * from "@/pages/Transportation/TransportationServices";
